import exiftool
import logging
import os

from datetime import datetime, UTC
from pathlib import Path
from .services import ReadFromService
from .data import CommonFields

logger = logging.getLogger(__name__)

class Metadata(ReadFromService):

    def __init__(self, file_path: Path, metadata: dict):
        """
        Initialize class variables.

        Parameters
        ----------
        file_path : Path
            Path to a file the metadata should be put into.
        metadata : dict
            Metadata for the file itself, passed already as a dict.
        """

        self.file_path = file_path
        self.metadata = metadata

    def _generate_geo_metadata(
        self,
        geo_data: dict | None = None,
        geo_data_exif: dict | None = None
    ) -> dict | None:
        """
        Function to generate GPS metadata for the file.

        Parameters
        ----------
        geo_data : dict or None
            Geo data generated by Google during the creation of the file, by default None.
        geo_data_exif : dict or None
            Actual geo data of the file during the creation, by default None.

        Returns
        -------
        dict or None
            Geo metadata or None.
        """

        if geo_data is not None:
            obj = geo_data
        elif geo_data_exif is not None:
            obj = geo_data_exif
        else:
            return None

        metadata = {}

        lat = self._get_field(obj=obj, keys='latitude', default=0.0)
        lon = self._get_field(obj=obj, keys='longitude', default=0.0)

        if lat == 0.0 and lon == 0.0:
            return None

        alt = self._get_field(obj=obj, keys="altitude", default=0.0)

        gps_latitude_ref = "S"
        if isinstance(lat, int) and lat >= 0:
            gps_latitude_ref = "N"

        gps_longitude_ref = "W"
        if isinstance(lon, int) and lon >= 0:
            gps_longitude_ref = "E"

        metadata.update({
            "GPSLatitude": lat,
            "GPSLongitude": lon,
            "GPSAltitude": alt,
            "GPSLatitudeRef": gps_latitude_ref,
            "GPSLongitudeRef": gps_longitude_ref,
        })

        return metadata

    @staticmethod
    def _format_date(timestamp: int | None) -> str | None:
        """
        Function to format a timestamp to a readable format.

        Parameters
        ----------
        timestamp : int or None
            Timestamp of the creation time of the file.

        Returns
        -------
        str or None
            Formatted date.
        """
        if not timestamp:
            return None

        try:
            from_timestamp = datetime.fromtimestamp(timestamp, tz=UTC).strftime("%Y:%m:%d %H:%M:%S")
            return from_timestamp
        except (TypeError, ValueError, Exception):
            return None

    def _extract_common_fields(self) -> CommonFields:
        """
        Function to extract common fields from the metadata JSON file.

        Returns
        -------
        CommonFields
            Common fields as a dataclass.
        """

        photo_taken_time = self._get_field(obj=self.metadata, keys=("photoTakenTime", "timestamp"))
        modification_time = self._get_field(obj=self.metadata, keys=("modificationTime", "timestamp"))
        description = self._get_field(obj=self.metadata, keys="description")
        device_type = self._get_field(obj=self.metadata, keys=("googlePhotosOrigin", "mobileUpload", "deviceType"))
        starred = self._get_field(obj=self.metadata, keys="starred")
        geo_data = self._get_field(obj=self.metadata, keys="geoData")
        geo_data_exif = self._get_field(obj=self.metadata, keys="geoDataExif")

        return CommonFields(
            photo_taken_time=self._to_int(value=photo_taken_time),
            modification_time=self._to_int(value=modification_time),
            description=description,
            device_type=device_type,
            starred=5 if starred else None,
            geo_data=geo_data,
            get_data_exif=geo_data_exif
        )

    @staticmethod
    def _set_file_dates(filepath: str | Path, timestamp: int) -> None:
        """
        Function to set system-wise modification date of the file,
        by doing that, other cloud storages such as Proton Photos, Synology Photos, Nextcloud Photos etc.
        can safely upload the file and sort it in a chronological order

        Parameters
        ----------
        filepath : str or Path
            Path to the file.
        timestamp : int
            Timestamp of the file from the metadata.
        """

        os.utime(filepath, (timestamp, timestamp))

    def _generate_photo_metadata(self, fields: CommonFields) -> dict:
        """
        Function to generate photo metadata.

        Parameters
        ----------
        fields : CommonFields
            Common fields that were extracted from _extract_common_fields() function.

        Returns
        -------
        dict
            Metadata of the photo.
        """

        metadata = {}

        if fields.photo_taken_time:
            metadata["AllDates"] = self._format_date(fields.photo_taken_time)

        if fields.modification_time:
            metadata["ModifyDate"] = self._format_date(fields.modification_time)

        if fields.description:
            metadata["ImageDescription"] = fields.description

        if fields.device_type:
            metadata["Make"] = fields.device_type

        if fields.starred:
            metadata["Rating"] = fields.starred

        geo = self._generate_geo_metadata(fields.geo_data, fields.get_data_exif)
        if geo:
            metadata.update(geo)

        return metadata

    def _generate_video_metadata(self, fields: CommonFields) -> dict:
        """
        Function to generate video metadata.

        Parameters
        ----------
        fields : CommonFields
            Common fields that were extracted from _extract_common_fields() function.
        Returns
        -------
        dict
            Metadata of the video.
        """

        metadata = {}

        if fields.photo_taken_time:
            date_str = self._format_date(fields.photo_taken_time)
            metadata["AllDates"] = date_str
            metadata["XMP:DateTimeOriginal"] = date_str

        if fields.modification_time:
            mod_str = self._format_date(fields.modification_time)
            metadata["ModifyDate"] = mod_str
            metadata["XMP:ModifyDate"] = mod_str

        if fields.description:
            metadata["QuickTime:Description"] = fields.description

        if fields.device_type:
            metadata["QuickTime:Make"] = fields.device_type

        geo = self._generate_geo_metadata(fields.geo_data, fields.get_data_exif)
        if geo:
            metadata.update(geo)

        return metadata

    def _generate_metadata(self) -> dict | None:
        """
        Function that orchestrates generation of the metadata depending on the file's extension.

        Returns
        -------
        dict or None
            Metadata if the extension exists in either of the formats or None.
        """

        extension = self._get_extension(self.file_path)
        common_fields = self._extract_common_fields()

        if extension in self.photo_formats:
            metadata = self._generate_photo_metadata(fields=common_fields)
        elif extension in self.video_formats:
            metadata = self._generate_video_metadata(fields=common_fields)
        else:
            logger.warning(f"Unsupported format: {extension} for file {self.file_path}")
            return None

        return metadata

    def restore(self) -> bool:
        """
        Function to restore metadata.

        Returns
        -------
        bool
            True if metadata was restored successfully, False otherwise.
        """
        with exiftool.ExifToolHelper(encoding="utf-8") as et:
            generate_metadata = self._generate_metadata()
            if not generate_metadata:
                return False

            common_fields = self._extract_common_fields()

            try:
                et.set_tags(
                    files=self.file_path,
                    tags=generate_metadata,
                    params=["-P", "-overwrite_original", "-n", "-charset", "UTF8"]
                )
                logger.info(f"Successfully restored metadata for: {self.file_path}")
                if common_fields.photo_taken_time:
                    self._set_file_dates(self.file_path, common_fields.photo_taken_time)
                return True
            except exiftool.exceptions.ExifToolExecuteError:
                if isinstance(et.last_stderr, str) and "minor" in et.last_stderr.lower():
                    logger.warning(f"Minor error in file {self.file_path}, retrying with -ignoreMinorErrors")
                    try:
                        et.set_tags(
                            files=self.file_path,
                            tags=generate_metadata,
                            params=["-P", "-overwrite_original", "-n", "-charset", "UTF8", "-ignoreMinorErrors"]
                        )
                        logger.info(f"Successfully restored metadata for: {self.file_path}")
                        if common_fields.photo_taken_time:
                            self._set_file_dates(self.file_path, common_fields.photo_taken_time)
                        return True
                    except exiftool.exceptions.ExifToolExecuteError:
                        logger.exception(f"Failed even with -ignoreMinorErrors for {self.file_path}")
                        return False

                logger.error(f"ExifTool stderr: {et.last_stderr}")
                logger.error(f"ExifTool stdout: {et.last_stdout}")
                logger.exception(f"Something went wrong during metadata insertion in file {self.file_path}")

                return False
